# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: (^tests/resources)
      - id: end-of-file-fixer
        exclude: (^tests/resources)
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: (^tests/resources)
      - id: check-toml
        exclude: (^tests/resources)
      - id: fix-byte-order-marker
        exclude: (^tests/resources)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(tests/resources|migrations/versions)
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: ^(tests/resources|migrations/versions)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
      - id: ruff
        exclude: ^resources
