[tool.black]
line-length = 120
include = '\.pyi?$'
extend-exclude = '''
/(
    resources
)/
'''


[tool.ruff]
line-length = 120
ignore = ["PLR0913", "B905"]
fix = true

[tool.ruff.mccabe]
max-complexity = 12

[tool.ruff.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
